language: node_js
node_js: 10
addons:
  chrome: stable
script:
- npm run lint
- npm run build
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:travis || travis_terminate 1;
  fi
after_success:
- frauci-update-version -d=skip && export TRAVIS_TAG=$(frauci-get-version)
- test "$TRAVIS_REPO_SLUG" = "Brightspace/continuous-professional-development" &&
  test "$TRAVIS_BRANCH" = "master" &&
  test "$TRAVIS_PULL_REQUEST" = "false" &&
  npm run publish:dev:cdn

env:
  global:
  - SAUCE_USERNAME: Horgan
  - REPO_NAME=continuous-professional-development
  - OWNER_NAME=Brightspace
  - secure: BMdO85U/oKS2Vht+uCI6AHbrROfyvfNgXoS4g4IhomtENL88DyoiXyPJHCEd57uneamk0xSLdizWo2esGaCYrNg6RkMHzQffJ3DR+v7i/nEepMzwM6HFOzBDVL2scuaHTY7JtsDZF/WQZ/7lfOT5LasuioRqlsXLsFLKU6/XXZHrD/PHmhbfniQMpBT6ajtf7Id4OU/5kdhwwc67gCnedsPyyj7wOvQEDrbTzAVRXLeViEg3noaShB5uOBf2tNZ8xhE1VY9nk2CWQbirjU3fqrZr9SfeDaJ8xKyJtv9m8DGV2/nGBAxJFvFRVNYxqie6BXdO5jvhIe7j52x/6piY35ci1A5zKzYbC/TD0Hs96DOlq3yiw5n+t3dPsOMw3ZgTndSbwFhlgv9YkjYiI2DFybH3am7BrGB5NVRausmQ8J4z5HWX10An2p0liW+7AN17F/94I+W9kNELgUyO+mRlpxHRhXoaJ4W7c4sN6uLeLcMpHyRPBevv+hHOJgfC6dfYLZADgTnLTOafrPw6iL7Ai/utKgog8bOPA32l8tjWY2WnIoLoLCto9cI+4JqwJJbvLtaG+H6q6Na9Y4r8bghD+diu806AVCEZBzt+FLQuqcGTFB6X1mn5gJ7aZXlmtkDC+Eq4WLu8O7CCUGJneNZNsf2ZpWmHlBMOvTSk+yMwsDw=
  - secure: ut3LeuTZGAd0xUmVCgwuc/x4+XkhuYb0KUegS6DUryUIrzC3SAGaXttw+lvdJtlI+SAdrTZnuAnxy/+O7Vu97NFRdm/C9alAofUpXUDDebyGI/OQrq8R0mg/oLd9tbRdoa+23kcWKPz/RaJenIeLKZd+aTcMawQkkazF7BviRKyyWQdTJ9tVEyE6hJIbUsWXnRrkSCebDEKz57xH9lMgIAT9Wd8fPZxRdhgjcYMiTWb9JA847vta8Tk9gTSPAYiLj6e/Oeausyx7SHEuyItamuPVOlkDC44w/uawZXHbOGL8d+dML0z+GRyYJJHdYyTXU7R+yJqNigQ0U7bcKor0IEZnPhTjeDqNQgbxbnsoVVGsLtM20yZ14n/8yCe0lxyNUOt+EPL88/mi5czCUHvJGq3eTd8Dv56BxvqFtOhLRT2e7zqxOuhApg0WtIsCuaC0H/dQflNypDHbSu95/oumyfbO9MUakWn48+gmQ7Po90IW1dOOPO5kqVf4Ug2bAY5Z7WZh+p99P6W731LMAW/WYpzyA9civnUwARHS/5P869IarXhmIuRa+SRbOuTxWDo0kluqvCkys3O9iG4WSj1Y+Rl2G41xQ8uJFJ0BaUdGqTE/3TZOlOJE43nG9kopSEQOe+cS6iVE6fopSW4zA8a7MLLjhL3+ZrpnNGq6ikCVrqI=
  #CDN_SECRET
  - secure: b+2O7IDuUfsBW8OmIOeODq0T315ik8lb6GwpZ8J89DZJK14FkYKxpi4ES+mKYru11JeSuhjGdCC5grmSRqIi+G82WnTrky3colYi95f2h+t1yc9TxfPz7Wr4E3dxqzOPm+f1vgjKP9hHLU/Y/nU+ocxJrp9y0pSKO20pHxJZCJlYc1Edlw3BVftQWtTG1ceGi2KwlJFqUnzUO/1YbO3qjWPqC7zXT+Z80ct/Xq82MauUESjbOFFjt7HZ/QshFnf3CgFfTRnb3QqCGBaPh6QHQiNwpMmKmE/8lHG0y02wWyKFfugfTfSSLVQp9s2AicWiLnMrKZWX6GaKvVfteYayTBRmfEkWHzoHr8lDZiDTgTElK7phanlACp9pfhNQVgDor9cCPlwEFb3NviREEKGTBydd2PsiisTE/HnyB5hb/Jrhp7o/He2HhkPlr6rEW7rAyq2buqBCILOWVhSpM4aJCS4pheQzzk/qi3r4tMAt/CxaJ2NIJbNzHlssYw1nWrENOUbDbqWG/StJ86FR2tMLn5O1Zw+i2mP2kJXsiDWkVA3mxUik9K4v7r5fUcr0PPTqLQswpALMBdclC81fjV7zcaalm2GJjAIYPyQgxYSzFOXc3sdFe0PtuF1UYcjYeoirm/sI4CEVMcbJOkoeEStis99yf5QiurMATN32W9EDjyY=
deploy:
- provider: releases
  api_key: "$GITHUB_RELEASE_TOKEN"
  on:
    tags: true
